services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y libpq-dev python3-dev
      pip install -r requirements.txt
    startCommand: gunicorn --worker-tmp-dir /dev/shm --workers 4 --threads 2 --timeout 60 bot:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.1
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
