services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y libpq-dev python3-dev
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
